### PR TITLE
Back button

### PR DESCRIPTION
**Pull request by connorwaslo**

### CODE REVIEW

**Comment by petermsouzajr** [comment]
on the intake screen where user enters first name last name, there is still a gear icon on every screen and there appears to be missing the 'back' button.

**Comment by connorwaslo** [comment]
> on the intake screen where user enters first name last name, there is still a gear icon on every screen and there appears to be missing the 'back' button.

The back button shouldn't exist on the very first screen. Doesn't really make sense to create your account and then go back. Resolved other issues.

**Comment by petermsouzajr** [comment]
can you please put the button there too, maybe someone could press the wrong button at the home screen and not be able to get back

**Review by petermsouzajr — APPROVED** [review]
👍

**Pull request merged**
